export const endpoints = {
  auth: {
    login: "/api/v1/auth/login",
    me: "/api/v1/auth/me",
    logout: "/api/v1/auth/logout"
  },
  portal: {
    home: "/api/v1/mobile/home",
    documents: "/api/v1/mobile/documents",
    document: (documentId: string) => `/api/v1/mobile/documents/${encodeURIComponent(documentId)}`,
    documentPreviewUrl: (documentId: string) => `/api/v1/documents/${encodeURIComponent(documentId)}/preview-url`,
    documentDownload: (documentId: string) => `/api/v1/documents/${encodeURIComponent(documentId)}/download`,
    courses: "/api/v1/mobile/courses",
    course: (courseId: string) => `/api/v1/mobile/courses/${encodeURIComponent(courseId)}`,
    courseProgress: (courseId: string) => `/api/v1/mobile/courses/${encodeURIComponent(courseId)}/progress`,
    courseComplete: (courseId: string) => `/api/v1/mobile/courses/${encodeURIComponent(courseId)}/complete`,
    profile: "/api/v1/mobile/me",
    briefs: "/api/v1/mobile/briefs",
    brief: (briefId: string) => `/api/v1/mobile/briefs/${encodeURIComponent(briefId)}`,
    briefFavorite: (briefId: string) => `/api/v1/mobile/briefs/${encodeURIComponent(briefId)}/favorite`,
    announcements: "/api/v1/mobile/announcements",
    announcement: (announcementId: string) => `/api/v1/mobile/announcements/${encodeURIComponent(announcementId)}`,
    announcementFavorite: (announcementId: string) => `/api/v1/mobile/announcements/${encodeURIComponent(announcementId)}/favorite`,
    newcomerContent: "/api/v1/mobile/newcomer/content",
    newcomerContentDetail: (contentId: string) => `/api/v1/mobile/newcomer/content/${encodeURIComponent(contentId)}`,
    newcomerContentFavorite: (contentId: string) => `/api/v1/mobile/newcomer/content/${encodeURIComponent(contentId)}/favorite`,
    myNewcomerTasks: "/api/v1/mobile/me/newcomer-tasks",
    myNewcomerTask: (taskId: string) => `/api/v1/mobile/me/newcomer-tasks/${encodeURIComponent(taskId)}`,
    completeMyNewcomerTask: (taskId: string) => `/api/v1/mobile/me/newcomer-tasks/${encodeURIComponent(taskId)}/complete`,
    forumHot: "/api/v1/mobile/forum-hot",
    forumHotPost: (postId: string) => `/api/v1/mobile/forum-hot/${encodeURIComponent(postId)}`,
    finance: "/api/v1/mobile/finance",
    financeInfo: (financeInfoId: string) => `/api/v1/mobile/finance/${encodeURIComponent(financeInfoId)}`,
    financeFavorite: (financeInfoId: string) => `/api/v1/mobile/finance/${encodeURIComponent(financeInfoId)}/favorite`
  },
  me: {
    profile: "/api/v1/me/profile",
    devices: "/api/v1/me/devices",
    device: (deviceId: string) => `/api/v1/me/devices/${encodeURIComponent(deviceId)}`,
    notificationSettings: "/api/v1/me/notification-settings",
    favorites: "/api/v1/me/favorites",
    favorite: (favoriteId: string) => `/api/v1/me/favorites/${encodeURIComponent(favoriteId)}`,
    downloads: "/api/v1/me/downloads",
    trainingProgress: "/api/v1/me/training-progress"
  },
  admin: {
    dashboard: "/api/v1/admin/mobile/dashboard",
    portalConfig: "/api/v1/admin/portal-config",
    categories: "/api/v1/admin/categories",
    category: (categoryId: string) => `/api/v1/admin/categories/${encodeURIComponent(categoryId)}`,
    enableCategory: (categoryId: string) => `/api/v1/admin/categories/${encodeURIComponent(categoryId)}/enable`,
    disableCategory: (categoryId: string) => `/api/v1/admin/categories/${encodeURIComponent(categoryId)}/disable`,
    tags: "/api/v1/admin/tags",
    tag: (tagId: string) => `/api/v1/admin/tags/${encodeURIComponent(tagId)}`,
    enableTag: (tagId: string) => `/api/v1/admin/tags/${encodeURIComponent(tagId)}/enable`,
    disableTag: (tagId: string) => `/api/v1/admin/tags/${encodeURIComponent(tagId)}/disable`,
    contents: "/api/v1/admin/contents",
    content: (contentId: string) => `/api/v1/admin/contents/${encodeURIComponent(contentId)}`,
    publishContent: (contentId: string) => `/api/v1/admin/contents/${encodeURIComponent(contentId)}/publish`,
    archiveContent: (contentId: string) => `/api/v1/admin/contents/${encodeURIComponent(contentId)}/archive`,
    documents: "/api/v1/admin/documents",
    document: (documentId: string) => `/api/v1/admin/documents/${encodeURIComponent(documentId)}`,
    publishDocument: (documentId: string) => `/api/v1/admin/documents/${encodeURIComponent(documentId)}/publish`,
    archiveDocument: (documentId: string) => `/api/v1/admin/documents/${encodeURIComponent(documentId)}/archive`,
    courses: "/api/v1/admin/courses",
    course: (courseId: string) => `/api/v1/admin/courses/${encodeURIComponent(courseId)}`,
    publishCourse: (courseId: string) => `/api/v1/admin/courses/${encodeURIComponent(courseId)}/publish`,
    archiveCourse: (courseId: string) => `/api/v1/admin/courses/${encodeURIComponent(courseId)}/archive`,
    newcomerTasks: "/api/v1/admin/newcomer-tasks",
    newcomerTask: (taskId: string) => `/api/v1/admin/newcomer-tasks/${encodeURIComponent(taskId)}`,
    enableNewcomerTask: (taskId: string) => `/api/v1/admin/newcomer-tasks/${encodeURIComponent(taskId)}/enable`,
    disableNewcomerTask: (taskId: string) => `/api/v1/admin/newcomer-tasks/${encodeURIComponent(taskId)}/disable`,
    users: "/api/v1/admin/users",
    user: (userId: string) => `/api/v1/admin/users/${encodeURIComponent(userId)}`,
    disableUser: (userId: string) => `/api/v1/admin/users/${encodeURIComponent(userId)}/disable`,
    userRole: (userId: string) => `/api/v1/admin/users/${encodeURIComponent(userId)}/roles`,
    roles: "/api/v1/admin/roles",
    auditLogs: "/api/v1/admin/audit-logs"
  }
} as const;
