from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


TEXT_SUFFIXES = {
    ".md",
    ".txt",
    ".json",
    ".jsonl",
    ".yaml",
    ".yml",
    ".py",
    ".ps1",
    ".mjs",
    ".js",
    ".ts",
}

DEFAULT_DENY_PATTERNS = [
    ("windows_absolute_path", r"(?i)\b[a-z]:[\\/][^\s\"'<>|]+"),
    ("home_relative_codex_path", r"(?i)(?:^|[\\/])users[\\/][^\\/]+[\\/]\.codex(?:[\\/]|$)"),
    ("checked_in_secret_artifact", r"(?i)\b(?:storageState\.json|cookies\.json|tokens?\.json|secret-manager export)\b"),
]

DEFAULT_SKIP_DIRS = {".git", "__pycache__", "node_modules", ".venv", "venv"}
FORBIDDEN_PACKAGE_PARTS = {"__pycache__"}
FORBIDDEN_PACKAGE_SUFFIXES = {".pyc", ".pyo"}
DEFAULT_PATTERN_FILE = "references/shareability-deny-patterns.json"


def iter_text_files(root: Path, skip_dirs: set[str], skip_files: set[Path]) -> list[Path]:
    files: list[Path] = []
    for path in root.rglob("*"):
        if any(part in skip_dirs for part in path.parts):
            continue
        if path.resolve() in skip_files:
            continue
        if path.is_file() and path.suffix.lower() in TEXT_SUFFIXES:
            files.append(path)
    return files


def find_forbidden_package_residue(root: Path) -> list[str]:
    findings: list[str] = []
    for path in root.rglob("*"):
        if any(part in FORBIDDEN_PACKAGE_PARTS for part in path.parts):
            findings.append(f"{path}: generated cache path must not be packaged")
            continue
        if path.is_file() and path.suffix.lower() in FORBIDDEN_PACKAGE_SUFFIXES:
            findings.append(f"{path}: generated bytecode file must not be packaged")
    return findings


def line_snippet(line: str, limit: int = 160) -> str:
    collapsed = " ".join(line.strip().split())
    if len(collapsed) <= limit:
        return collapsed
    return collapsed[: limit - 3] + "..."


def is_internal_pattern_definition(path: Path, label: str, line: str) -> bool:
    return (
        path.name == "check_shareability_residue.py"
        and label == "checked_in_secret_artifact"
        and "checked_in_secret_artifact" in line
    )


def load_pattern_file(path: Path) -> list[tuple[str, str]]:
    if not path.exists():
        return []
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ValueError(f"invalid deny-pattern JSON in {path}: {exc}") from exc

    patterns: list[tuple[str, str]] = []
    for index, item in enumerate(payload.get("deny_patterns", []), start=1):
        if not isinstance(item, dict):
            raise ValueError(f"deny pattern #{index} in {path} must be an object")
        label = str(item.get("label") or f"deny_pattern_{index}")
        pattern = str(item.get("pattern") or "")
        if not pattern:
            raise ValueError(f"deny pattern #{index} in {path} is missing pattern")
        patterns.append((label, pattern))
    return patterns


def compile_patterns(raw_patterns: list[tuple[str, str]]) -> list[tuple[str, re.Pattern[str]]]:
    patterns: list[tuple[str, re.Pattern[str]]] = []
    for label, pattern in DEFAULT_DENY_PATTERNS:
        patterns.append((label, re.compile(pattern)))
    for label, pattern in raw_patterns:
        patterns.append((label, re.compile(pattern, re.IGNORECASE)))
    return patterns


def main() -> int:
    parser = argparse.ArgumentParser(
        description=(
            "Scan a skill package for machine-local residue before sharing. "
            "Pass --deny-pattern for source-project terms that should not remain "
            "in a white-labeled package."
        )
    )
    parser.add_argument("--skill-dir", default=str(Path(__file__).resolve().parents[1]))
    parser.add_argument(
        "--deny-pattern",
        action="append",
        default=[],
        help="Additional regex that must not appear in shareable skill files. Repeat as needed.",
    )
    parser.add_argument(
        "--deny-pattern-file",
        default=DEFAULT_PATTERN_FILE,
        help=(
            "JSON file with deny_patterns entries, relative to --skill-dir unless "
            "absolute. Defaults to references/shareability-deny-patterns.json."
        ),
    )
    parser.add_argument(
        "--skip-dir",
        action="append",
        default=[],
        help="Directory name to skip in addition to default generated/vendor folders.",
    )
    args = parser.parse_args()

    skill_dir = Path(args.skill_dir)
    if not skill_dir.exists():
        print(f"[FAIL] missing skill directory: {skill_dir}", file=sys.stderr)
        return 1

    skip_dirs = DEFAULT_SKIP_DIRS.union(args.skip_dir)
    pattern_file = Path(args.deny_pattern_file)
    if not pattern_file.is_absolute():
        pattern_file = skill_dir / pattern_file
    skip_files = {pattern_file.resolve()} if pattern_file.exists() else set()
    try:
        configured_patterns = load_pattern_file(pattern_file)
        cli_patterns = [(f"custom_deny_{index}", pattern) for index, pattern in enumerate(args.deny_pattern, start=1)]
        patterns = compile_patterns(configured_patterns + cli_patterns)
    except (ValueError, re.error) as exc:
        print(f"[FAIL] {exc}", file=sys.stderr)
        return 1
    findings: list[str] = find_forbidden_package_residue(skill_dir)

    for path in iter_text_files(skill_dir, skip_dirs, skip_files):
        try:
            lines = path.read_text(encoding="utf-8").splitlines()
        except UnicodeDecodeError:
            findings.append(f"{path}: unreadable as UTF-8 text")
            continue
        for line_no, line in enumerate(lines, start=1):
            for label, pattern in patterns:
                if pattern.search(line):
                    if is_internal_pattern_definition(path, label, line):
                        continue
                    findings.append(
                        f"{path}:{line_no}: {label}: {line_snippet(line)}"
                    )

    if findings:
        print("[FAIL] shareability residue found", file=sys.stderr)
        for finding in findings:
            print(f"- {finding}", file=sys.stderr)
        return 1

    print("[PASS] Skill shareability residue scan passed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
